services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pashupati-views-hotel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - pashupati-views-hotel-network
 
  nginx:
    image: nginx:1.27-alpine
    container_name: pashupati-views-hotel-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pashupati-views-hotel-network

  mysql:
    image: mysql:8.0
    container_name: pashupati-views-hotel-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-pashupatihotel}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pashupatihotel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-pashupatihotel}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - pashupati-views-hotel-network

volumes:
  db-data:

networks:
  pashupati-views-hotel-network:

