version: "3"
services:
  tms-cmd:   
    image: 
    user: "1000:1000"
    logging:
      driver: syslog
      options:
        syslog-address: 
        syslog-facility: 'daemon'
        tag: 
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        order: start-first
      placement:
        constraints:
          - node.role == worker
    networks:
      - 
    env_file:
      - .env
    environment:
      - TZ=Asia/Kathmandu 
      
networks:
  
